version: 2.1

orbs:
  node: circleci/node@3.0.0

commands:
  setup-node-and-yarn-install-with-cache:
    steps:
      - node/install:
          install-yarn: true
          node-version: 14.8.0
      - node/install-packages:
          pkg-manager: yarn
          cache-key: yarn.lock

jobs:
  lint-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - setup-node-and-yarn-install-with-cache
      - run:
          name: Run tests
          command: npm run test

workflows:
  run-ci:
    jobs:
      - lint-and-test