version: "3"
services:
  mysql:
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "ricky"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3308:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/data:/var/lib/mysql
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - ./redis/data:/data
